driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY'] %>
  security_group_ids:  <%= ENV['AWS_SECURITY_GROUPS'] %>
  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  require_chef_omnibus: true
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  associate_public_ip: false
  interface: private
  tags:
    OWNER: <%= ENV['AWS_OWNER_TAG'] %>
    Name: <%= ENV['AWS_NAME_TAG'] %>

provisioner:
  name: chef_zero
  attributes:
    fake_databags:
      - data_bag: 'vault'
        content:
          id: 'splunk__default'
          auth: 'admin:notarealpassword'
transport:
  ssh_key: <%= ENV['SSH_KEY_PATH'] %><%= ENV['AWS_SSH_KEY'] %>.pem

platforms:
  - name: centos-6.7
    driver:
      image_id: <%= ENV['AWS_CENTOS6_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS6_USERNAME'] %>
  - name: centos-7.1
    driver:
      image_id: <%= ENV['AWS_CENTOS7_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_CENTOS7_USERNAME'] %>
  - name: ubuntu-12.04
    driver:
      image_id: <%= ENV['AWS_UBUNTU12_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_UBUNTU12_USERNAME'] %>
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV['AWS_UBUNTU14_AMI_ID'] %>
      instance_type: <%= ENV['LINUX_INSTANCE_SIZE'] %>
      user_data: <%= ENV['LINUX_USER_DATA_PATH'] %>
    transport:
      username: <%= ENV['AWS_UBUNTU14_USERNAME'] %>
    run_list:
      - recipe[apt::default]
  - name: windows-2012r2
    driver:
      image_id: <%= ENV['AWS_WINDOWS2012R2_AMI_ID'] %>
      instance_type: <%= ENV['WINDOWS_INSTANCE_SIZE'] %>
      user_data: <%= ENV['WINDOWS_USER_DATA_PATH'] %>
      require_chef_omnibus: 12.5.1

suites:
  - name: windows_client
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[chef-splunk::default]
      - recipe[test::prerequisites]
      - recipe[test::postrequisites]
    attributes:
      dev_mode: true
      splunk:
        setup_auth: false
        server:
          runasroot: false
        accept_license: true
        indexers_group1:
          splunk_servers: '192.168.10.1:9997, 192.168.10.2:9997, 192.168.10.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        indexers_group2:
          splunk_servers: '192.168.20.1:9997, 192.168.20.2:9997, 192.168.20.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        inputs_conf:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                source: tcp:123123
    includes:
      - windows-2012r2

  - name: linux_client
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[chef-splunk::default]
      - recipe[test::prerequisites]
      - recipe[test::postrequisites]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        accept_license: true
        indexers_group1:
          splunk_servers: '192.168.10.1:9997, 192.168.10.2:9997, 192.168.10.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        indexers_group2:
          splunk_servers: '192.168.20.1:9997, 192.168.20.2:9997, 192.168.20.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        inputs_conf:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                source: tcp:123123
    excludes:
      - windows-2012r2
      - ubuntu-12.04
      - ubuntu-14.04

  - name: forwarder_package
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[yum-gd]
      - recipe[chef-splunk::default]
      - recipe[test::prerequisites]
      - recipe[test::postrequisites]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        accept_license: true
        forwarder:
          package_install: true
        indexers_group1:
          splunk_servers: '192.168.10.1:9997, 192.168.10.2:9997, 192.168.10.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        indexers_group2:
          splunk_servers: '192.168.20.1:9997, 192.168.20.2:9997, 192.168.20.3:9997'
          outputs_conf:
            sslCommonNameToCheck: sslCommonName
            sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
            sslPassword: password
            sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
            sslVerifyServerCert: false
        inputs_conf:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                source: tcp:123123
    excludes:
      - windows-2012r2
      - ubuntu-12.04
      - ubuntu-14.04

  - name: server
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[chef-splunk::default]
      - recipe[test::prerequisites]
      - recipe[test::postrequisites]
    attributes:
      dev_mode: true
      splunk:
        server:
        accept_license: true
        is_server: true
    excludes:
      - windows-2012r2
      - centos-6.7
      - centos-7.1
      - ubuntu-12.04
      - ubuntu-14.04

  - name: server-runas-splunk
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[chef-splunk::default]
    attributes:
      dev_mode: true
      splunk:
        server:
          runasroot: false
        is_server: true
        accept_license: true
        ssl_options:
          enable_ssl: true
        web_port: 8443
    excludes:
      - windows-2012r2
      - centos-6.7
      - centos-7.1
      - ubuntu-12.04
      - ubuntu-14.04

  - name: disabled
    run_list:
      - recipe[kitchen-test-helper]
      - recipe[chef-splunk::default]
    attributes:
      splunk:
        disabled: true
    excludes:
      - windows-2012r2
      - centos-6.7
      - centos-7.1
      - ubuntu-12.04
      - ubuntu-14.04
